POST localhost:5678/api/index/batch
Content-Type: application/json

[
  {
    "id": 4194561,
    "text": "人一生必须培养的好习惯有哪些？",
    "document": {
      "category": "news_culture",
      "cid": "101",
      "id": "6422885744473276673",
      "title": "人一生必须培养的好习惯有哪些？"
    }
  },
  {
    "id": 29360647,
    "text": "去茶店喝茶，这些坏习惯一定要改",
    "document": {
      "category": "news_culture",
      "cid": "101",
      "id": "6526026244490789383",
      "title": "去茶店喝茶，这些坏习惯一定要改"
    }
  },
  {
    "id": 482345479,
    "text": "终于等到你 大连一方迎中超首胜",
    "document": {
      "category": "news_sports",
      "cid": "103",
      "id": "6552361064552464903",
      "title": "终于等到你 大连一方迎中超首胜"
    }
  },
  {
    "id": 2273313284,
    "text": "范丞丞人气有多高？付费自拍睡一觉起来就躺赚了480万",
    "document": {
      "category": "news_entertainment",
      "cid": "102",
      "id": "6552353988237328900",
      "title": "范丞丞人气有多高？付费自拍睡一觉起来就躺赚了480万"
    }
  },
  {
    "id": 2688549390,
    "text": "比特币交易平台官网",
    "document": {
      "category": "news_finance",
      "cid": "104",
      "id": "6552399416521654798",
      "title": "比特币交易平台官网"
    }
  },
  {
    "id": 3162505486,
    "text": "有哪些优秀的阅读习惯和技巧？",
    "document": {
      "category": "news_culture",
      "cid": "101",
      "id": "6552470670503051534",
      "title": "有哪些优秀的阅读习惯和技巧？"
    }
  },
  {
    "id": 3602907656,
    "text": "大学英语四级考试500个高频词汇",
    "document": {
      "category": "news_edu",
      "cid": "108",
      "id": "6552332699414037000",
      "title": "大学英语四级考试500个高频词汇"
    }
  },
  {
    "id": 3921674756,
    "text": "农村深山里的这种植物，看似其貌不扬，它竟还有这样的功效！",
    "document": {
      "category": "news_agriculture",
      "cid": "115",
      "id": "6552380653042663940",
      "title": "农村深山里的这种植物，看似其貌不扬，它竟还有这样的功效！"
    }
  },
  {
    "id": 4034920967,
    "text": "北大百廿燕归来",
    "document": {
      "category": "news_edu",
      "cid": "108",
      "id": "6552368906420355591",
      "title": "北大百廿燕归来"
    }
  }
]

